webissues/urls.py
from django.conf.urls import include, url
from track.views import *
from track import views
from django.contrib.auth.views import logout,login
from track.form import *
from rest_framework import routers
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf.urls import handler404

router=routers.DefaultRouter()
router.register('issue',IssueSet)
router.register('project',ProjectSet)
router.register('user',UserSet)


urlpatterns = [
    #url('',include('track.url',namespace='track')),
    url(r'^api/',include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',index,name='index'),
    url(r'^index/',index,name='index'),
    url(r'^accounts/login/',views.login,name='login'),
    url(r'^accounts/auth/',auth_view,name='auth'),
    url(r'^nav',TemplateView.as_view(template_name='new_nav.html')),
    url(r'^accounts/logout/',logout,{'template_name':'registration/logout.html'}),
    url(r'^accounts/profile/',profile,name='profile'),
    url(r'^accounts/auth/',auth_view,name='authview'),
    url(r'^total',noproject,name='number_of_project'),
    url(r'^issues/(?P<pk>\d+)/delete',delete_issue,name='delete_issue'),
    url(r'^issues/(?P<pk>\d+)/edit',edit,name='project_edit'),
    url(r'^issues/(?P<pk>\d+)$',issue_detail,name='issue_details'),
    url(r'^updateproject/(?P<pk>\d+)$',projectupdate,name='project_edit'),
    url(r'^project/(?P<pk>\d+)$',projectis_issue,name='project_issue'),
    url(r'^create/(?P<pk>\d+)$',create,name='create_issue'),
    url(r'^create/$',selectproject,name='project_selection'),
    url(r'^new/',new,name='new'),
    url(r'^edit/',edit,name='edit'),
    url(r'^delete/(?P<pk>\d+)$',delete_issues,name='delete'),
    url(r'^export',export_csv,name='csv'),
    url(r'^create/project$',create_project,name='create_project'),
    url(r'^search',searching,name='search'),
    url(r'^grade',grade,name='gradecard'),
    url(r'result',result,name='result'),
    url(r'^api/',include('rest_framework.urls',namespace='rest_framework'))
]

webissues/webissues/urls.py
from django.conf.urls import include, url
from track.views import *
#from django.contrib.auth import views
from track import views
from django.contrib.auth.views import login, logout
from django.contrib.auth.views import logout,login
from track.form import *
from rest_framework import routers
from django.views.generic import TemplateView
from django.contrib import admin

router=routers.DefaultRouter()
router.register('issue',IssueSet)
router.register('project',ProjectSet)
router.register('user',UserSet)

urlpatterns = [
    #url('',include('track.url',namespace='track')),
    url(r'^api/',include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',index,name='index'),
    url(r'^index/',index,name='index'),
    url(r'^accounts/login/',views.login,name='login'),
    #url(r'login',views.loginview,name='loginview'),
    #url(r'^accounts/login',views.login,{'template_name': 'registration/logins.html', 'authentication_form': LoginForm}),
    #url(r'accounts/logout',views.logout,{'next_page':'/login'}),
    #url(r'^accounts/login',login.as_view(),name='login'),
    url(r'^accounts/auth/',auth_view,name='auth'),
    url(r'^nav',TemplateView.as_view(template_name='new_nav.html')),
    url(r'^accounts/logout/',logout,{'template_name':'registration/logout.html'}),
    url(r'^accounts/profile/',profile,name='profile'),
    url(r'^accounts/auth/',auth_view,name='authview'),
    url(r'^total',noproject,name='number_of_project'),
    url(r'^issues/(?P<pk>\d+)$',edit,name='issue_edit'),
    url(r'^updateproject/(?P<pk>\d+)$',projectupdate,name='project_edit'),
    url(r'^project/(?P<pk>\d+)$',projectis_issue,name='project_issue'),
    url(r'^create/(?P<pk>\d+)$',create,name='create_issue'),
    url(r'^create/$',selectproject,name='project_selection'),
    url('^new/',new,name='new'),
    url(r'^edit/',edit,name='edit'),
    url(r'^delete/(?P<pk>\d+)$',delete_issue,name='delete_issue'),
    url(r'^test',export_csv,name='csv'),
    url(r'^create/project$',create_project,name='create_project'),
    url(r'^api/',include('rest_framework.urls',namespace='rest_framework'))
]

webissues/track/models.py
from django.db import models
from datetime import datetime
from track.full import *
from django.contrib.auth.models import User
# Create your models here.

class project(models.Model):
    name=models.CharField(max_length=20)
    description=models.TextField()
    def __str__(self):
        return self.name


class issue(models.Model):
    nothing = '----'
    new ='New'
    inprocess='In Process'
    complete='Complete'
    choices=(
        (new , 'New'),
        (inprocess,'In Process'),
        (complete,'Complete'),
    )

    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    created_date=models.DateTimeField(default=datetime.now,blank=True)
    #created_by=models.ForeignKey(User,on_delete=models.CASCADE)
    created_by=models.CharField(max_length=20,blank=True)
    status=models.CharField(max_length=10,choices=choices,default=nothing,blank=True)
    comment=models.TextField(blank=True)
    modify_by=models.CharField(max_length=20,blank=True)
    #assigned_to=models.ForeignKey(User)
    #assigned_to=models.OneToOneField(User,on_delete=models.CASCADE)
    #assigned_to=models.OneToOneField(User,on_delete=models.CASCADE)
    priority=models.IntegerField(null=True)
    tat=models.IntegerField(null=True)
    assign=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    project_id=models.ForeignKey(project,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return str(self.id)+' '+self.name

webissues/templates/base.html
{% load staticfiles %}
<html lang="en">
<head id="header">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
</head>
    <title>{% block title %} {% endblock %}</title>
    <!--<link rel="stylesheet" type="text/css" href="/static/style.css">
    <!--<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">inc
    <script src="js/bootstrap.min.js"></script>-->
{% include "js.html" %}
{% include 'css.html' %}

<body style="font-size: 14px">

{% include 'new_nav.html' %}

<div  style="padding-bottom: .6cm;width: 98%">
<div class="body content" style="margin-left: 1%;">
    <div class="row">
        <div class="col-sm-2">
            <div class="sidecontent">
                {% block sidecontent %}
                {% endblock %}
            </div>
        </div>
        <div class="col-md-9">
            <div>
                {% block content %}
                {% endblock %}
            </div>

        </div>
    </div>
</div>
</div>
</body><!--
<footer id="footer">
    <p>Hi this is designed by me</p>
</footer>-->
</html>

webissues/templates/css.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'style/bootstrap-theme.min.css' %}">
<link rel="stylesheet" href="{% static 'style/style.css' %}">

webissues/templates/dashboard.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}Dashboard{% endblock %}

{% block sidecontent %}
<div class="container" style="">
<div style="#777777;">
<div><h2>Projects</h2></div>
<div style="height: 20px;margin-top: 10px;"><h4><a href="/totalproject">All Projects</a> </h4></div>
{% for i in project %}
    {% if i.id == project_name.id %}
    <div><h5><b>{{ i }}</b></h5></div>
    {% else %}
<div ><h5></b><a href="/project/{{ i.id }}">{{ i.name }}</a></h5></div>{% endif %}
{% endfor %}
{% if user.groups.get.name == 'Associate' %}

{% else %}
<div><a href="/create/project">Add New</a></div>
{% endif %}
</div>
</div>
{% endblock %}



{% block content %}
    <div style="background-color: transparent">
<div style="font-size: 2em;height: 120px;padding-top: 10px;">
        <table width="80%">
        <tr>
        {% if project_name.name %}
                <td colspan="2" align="center"><h2>{{ project_name.name }}</h2></td>
                {% else %}
                <td colspan="2" align="center"><h2>All Project</h2></td>
                {% endif %}
        </tr>
            <tr style="font-size: 20px;">
                {% if user.groups.get.name == 'Associate' %}
                <td><a href="/export/">Export to CSV</a></td>

                {% else %}
                <td style="float: left;padding-left: 50px;"><a href="/create/{{ project_name.id }}">Add issue</a> </td>
                <td style="float: right"><a href="/export/">Export to CSV</a></td>
                {% endif %}

                <!--<td style="padding-left: 7cm">Export to CSV</td>-->

            </tr>
        </table>

    </div>
    <div >

    <div>
    <table class="table">
    <tr style="background-color: dimgrey;color: white">
        <th>ID</th>
        <th>Name</th>
        <th>Comment</th>
        <th>Created Date</th>
        <th>Created_By</th>
        <th>Status</th>
        <th>Priority</th>
        <th>Assigned to</th>
        <th>Modify by</th>
        {% if user.groups.get.name == 'Associate' %}
        {% else %}
        <th>Action</th>
        {% endif %}
    </tr>
    {% for i in query %}
    <tr>
        <td>{{ i.id }}</td>
        <td><a href="/issues/{{ i.id }}">{{ i.name }}</a></td>
        <td>{{ i.comment }}</td>
        <td>{{ i.created_date }}</td>
        <td>{{ i.created_by }}</td>
        <td>{{ i.status }}</td>
        <td>{{ i.priority }}</td>
        <td>{{ i.assign.get_full_name }}</td>
        <td>{{ i.modify_by }}</td>
        {% if user.groups.get.name == 'Associate' %}
        {% else %}
        <td><a href="/delete/{{ i.id }}"><input type="button" class="btn btn-primary" value="Delete"></a></td>
        {% endif %}
    </tr>
    {% endfor %}

   </table>
    </div>
</div>
    </div>



{% endblock %}

webissues/templates/edit_issue.html
{% extends 'base.html' %}
{% load bootstrap3  %}
{% block title %}
{% if create %}
    Create Issue
{% elif project %}
    Create Project
    {% elif updateproject %}
    Update Project
    {% else %}
    Update Issue
    {% endif %}
{% endblock %}

{% block content %}
    {% if cannot %}
    <h3>You don't have permission to this</h3>
    {% else %}

{% if form.error %}
    <p>invalid details</p>
    {% endif %}
{% if error %}
<h2>invalid details</h2>
{% endif %}
<div class="col-sm-5">

{% if create %}
    <h2>Create New Issue</h2>
    <form action="/create/{{ proj }}" method="POST">
{% elif project %}
    <h2>Create New Project</h2>
    <form action="/create/project" method="POST">
{% elif updateproject %}
    <h2>Update Project</h2>
    <form action="/updateproject/{{ temp.id }}" method="POST">
{% else %}
    <h2>Update Issue</h2>
<form action="/issues/{{ task.id }}" method="POST">


{% endif %}

    {% csrf_token %}
{% bootstrap_form form layout='' %}
    {% if updateproject  %}
        <div>
    <div class="col-md-6"><input class="btn btn-primary btn-block" type="submit" value="update"></div>
    <div class="col-md-6"><input class="btn-danger btn btn-block" type="submit" value="delete"></div>

        <!--<input type="submit" value="submit" class="btn btn-primary btn-block">-->
        </div>
        <div>
        &nbsp;
        </div>
    {% else %}
    <input type="submit" value="submit" class="btn btn-primary btn-block">
    {% endif %}
<br>
</form>
</div>
{% endif %}
{% endblock %}

webissues/templates/footer.html
<div class="navbar navbar-inverse bottom "  id="menu">by me</div>

webissues/templates/issue_details.html
{% extends 'base.html' %}
{% block content %}
        <div class="container">

        <ul style="font-size: 2em;">
        <li>Name :<input type="text" value="{{ obj.name }}"/></li>
        <li>Created Date : {{ obj.date }}</li>
        <li>Created By : {{ obj.created_by }}</li>
        <li>Status : {{ obj.status }}</li>
        <li>comments : {{ obj.comment }}</li>
        <li>Modify_by : {{ obj.modify_by }}</li>
        <li>Priority : {{ obj.priority }}</li>
        <li>TAT : {{ obj.tat }}</li>
        <li>Assigned To : {{ obj.assign }}</li>
        </ul>
        </div>
{% endblock %}

webissues/templates/js.html
{% load staticfiles %}
<script src="{% static 'js/angular.js' %}"></script>
<script src="{% static 'js/app/app.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>

webissues/templates/nav.html
{% include 'css.html' %}
{% include 'js.html' %}

<div>

            <div class="navbar navbar-inverse navbar-fixed-top " id="menu">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".inn">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    <a href="/accounts/profile" class="navbar-brand">
                        {{ user.first_name }} {{ name }}
                    </a>
                    </div>

                    <div class="navbar-collapse collapse navbar-right">
                        <div class="in inn">
                        <ul class="nav navbar-nav">
                            <li ><a href="/index">HOME</a></li>
                             <li><a href="/create">CREATE</a></li>
                            <li><a href="#faculty-sec">FACULTY</a></li>
                             <li><a href="#course-sec">COURSES</a></li>
                             <li><a href="#contact-sec">CONTACT</a></li>
                        </ul>
                            </div>
                    </div>

                    <form class="navbar-search col-sm-5 docs-search" ng-submit="submit()">

                        <span class="glyphicon glyphicon-search search-icon "></span>
                        <input type="text"
                                name="q"
                                class="search-query"
                                placeholder="search"
                                autocomplete="off">

                    </form>

                </div>
            </div>

            <div class="navbar navbar-inverse text-hide" id="menu">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sss">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>

                    <div class="navbar-collapse collapse move-me navbar-right" id="sss">
                        <ul class="nav navbar-nav">
                            <li ><a href="/">HOME</a></li>
                             <li><a href="/new">CREATE</a></li>
                            <li><a href="#faculty-sec">FACULTY</a></li>
                             <li><a href="#course-sec">COURSES</a></li>
                             <li><a href="#contact-sec">CONTACT</a></li>
                        </ul>
                    </div>
                    <form class="navbar-search col-sm-5 docs-search" ng-submit="submit()">
                        <span class="glyphicon glyphicon-search search-icon "></span>
                        <input type="text"
                                name="q"
                                class="search-query"
                                placeholder="search"
                                autocomplete="off">
                    </form>
                </div>
            </div>

</div>

webissues/templates/new_nav.html
{% load staticfiles %}
{% include 'css.html' %}
{% include 'js.html' %}
    <div class="navbar navbar-inverse navbar-fixed-top " id="menu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sss">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand"><a href="/"><img src="{% static 'logo/webissues-logo.png'%}" height="25"></a></div>
            </div>

            <div class="navbar-collapse collapse move-me navbar-right" id="sss">
                <ul class="nav navbar-nav">
                    <li ><a href="/index">Home</a></li>
                    {% if user.groups.get.name == 'Associate' %}
                        {% else %}
                     <li><a href="/create">Create</a></li>
                    {% endif %}
                    <li><a href="/accounts/profile">{{ user.first_name }}{{ name.first_name }}</a></li>
                     <li><a href="/accounts/logout">Logout</a></li>
                </ul>
            </div>
            <form class="navbar-search col-sm-5 docs-search" ng-submit="submit()">
                <span class="glyphicon glyphicon-search search-icon "></span>
                <input type="text"
                        name="q"
                        class="search-query"
                        placeholder="search"
                       doc-search-input
                        autocomplete="off">
            </form>

        </div>
    </div>
    <div class="navbar hide-text" id="menu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sss">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <div class="navbar-collapse collapse move-me navbar-right" id="sss">
                <ul class="nav navbar-nav">
                    <li ><a href="/">HOME</a></li>
                     <li><a href="/new">CREATE</a></li>
                    <li><a href="#faculty-sec">FACULTY</a></li>
                     <li><a href="#course-sec">COURSES</a></li>
                     <li><a href="#contact-sec">CONTACT</a></li>
                </ul>
            </div>
            <form class="navbar-search col-sm-5 docs-search" ng-submit="submit()">
                <span class="glyphicon glyphicon-search search-icon "></span>
                <input type="text"
                        name="q"
                        class="search-query"
                        placeholder="search"
                       doc-search-input
                        autocomplete="off">
            </form>

        </div>
    </div>

webissues/templates/orig.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<title>{% block title %} {% endblock %}</title>


<body>
<div class="container">
{% include 'new_nav.html' %}
        <div>
                    {% block content %}
                    {% endblock %}
        </div>
</body>
</html>

webissues/templates/project_option.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}

    {% if only %}

        <div class="col-md-8">
    <table class="table" align="center">
    <tr align="center">
        <td><b>Projects</b></td>
        <td><b>Number of Issue</b></td>
    </tr>
     {% for i in project %}
    <tr align="center">
       <td><a href="/project/{{ i.id }}">{{ i.name }}</a></td>
        <td> {{ i.issue_set.count }}</td>
    </tr>
    {% endfor %}
    <tr align="center">
        <td>Tatal Projects : {{ project.count }}</td>
        <td>Total Issue : {{ issue.count }}</td>
    </tr>
    </table>
        </div>
    {% else %}

<h3>Please Select a Project in which you want create issue</h3>
{% for i in project %}
    <h4><a href="/create/{{ i.id }}">{{ i.name }}</a></h4>
{% endfor %}
    {% endif %}
{% endblock %}

webissues/templates/search.html
{% include 'js.html' %}
{% include 'css.html' %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>Dropdown Searchbox</h2>
    </div>
    <div class="panel-body">
      <div class="row">
      	<div class="col-md-6">
          <div class="form-horizontal">
            <div class="input-group">
              <div class="ddl-select input-group-btn">
                <select id="ddlsearch" class="selectpicker form-control" data-style="btn-primary btn">
                  <option value="" data-hidden="true" class="ddl-title">SEARCH</option>
                  <option value="google">Google</option>
                  <option value="yahoo">Yahoo</option>
                  <option value="bing">Bing</option>
                </select>
              </div>
              <input id="txtkey" class="form-control" placeholder="Enter here" aria-describedby="ddlsearch" type="text">
              <span class="input-group-btn">
                <button id="btn-search" class="btn btn-info btn-primary" type="button"><i class="fa fa-search fa-fw"></i></button>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-body">
      	<div class="row">
          <div id="sresult" class="well"></div>
          <redirect <="" div="">
      </redirect></div>
    </div>
  </div>
</div></div>


            <div id="push"></div>
        

webissues/templates/validation.html
{% include 'js.html' %}
<html>
<head></head>
<body ng-app="myapp">

<div ng-controller="HelloController as ct" >
    <h2>Welcome {{helloTo.title}} to the my world</h2>
    <h3>{{helloTo.body}}</h3>
    <button ng-click=ct.cl() class="btn btn-danger" >Click me</button>
    <!--<img src="header.jpg" height="240" ng-click="ct.cl()">-->
<p>Total time button clicked {{ct.counter}}</p>
    </div>
</body>
</html>

<!--
<script>
angular.module("myapp", [])
.controller("HelloController", function($scope) {
$scope.helloTo = {};
$scope.helloTo.title = "AngularJS";
$scope.helloTo.body="This is body of anglar";
this.counter=0;
this.cl=function(){
this.counter++;
}
});
</script>-->